<a href="https://colab.research.google.com/github/ruthin1912/machinelearning/blob/main/20125_week_3_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5]) #1-d array
arr

array([1, 2, 3, 4, 5])

In [3]:
arr = np.array([[1,2,3,4],[5,6,7,8]]) #2-d array
print(arr)
print(arr.ndim) #printing no.of dimensions

[[1 2 3 4]
 [5 6 7 8]]
2


In [4]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[1,2,3,4]]]) #3-d array
print(arr)
print(arr.ndim)

[[[1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]]]
3


In [5]:
arr = np.array([1,2,3,4]) 
print(arr[3])

4


In [6]:
arr = np.array([1,2,3,4]) 
print(arr[3]+arr[1])

6


In [7]:
arr = np.array([[1,2,3,4],[5,6,7,8]]) #2-d array position of element
print(arr[0,1])

2


In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) #3-d array position of element
print(arr[0,1,2])

6


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[22,33,44,55]]) #Print the last element from the 2nd dim:
print(arr[1,-1])
print(arr)

8
[[ 1  2  3  4]
 [ 5  6  7  8]
 [22 33 44 55]]


In [9]:
# Flattening the arrays (Converting a multidimensional array into a 1D array)
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

[1 2 3 4 5 6]
1
(6,)


In [10]:
# Mean, Median and Standard deviation
a = np.arange(5,50,2)
print(a)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

# minimum along a column
print('Min :',np.min(a))
# maximum along a row
print('Max :',np.max(a))

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
Mean : 27.0
Standard deviation : 13.2664991614216
Median : 27.0
Min : 5
Max : 49


In [11]:
# Array Arithmetic
a = np.array([[3, 2, 4], [5, 0, 1], [2, 5, 8]])
b = np.array([[1, 0, 5], [2, 3, 7], [6, 4, 5]])

print(a+2)
print(a-1)
print(a*5)
print(a/2)

c = a + b
print(c)

d = a - b
print(d)

e = a * b
print(e)

[[ 5  4  6]
 [ 7  2  3]
 [ 4  7 10]]
[[ 2  1  3]
 [ 4 -1  0]
 [ 1  4  7]]
[[15 10 20]
 [25  0  5]
 [10 25 40]]
[[1.5 1.  2. ]
 [2.5 0.  0.5]
 [1.  2.5 4. ]]
[[ 4  2  9]
 [ 7  3  8]
 [ 8  9 13]]
[[ 2  2 -1]
 [ 3 -3 -6]
 [-4  1  3]]
[[ 3  0 20]
 [10  0  7]
 [12 20 40]]


In [12]:
# NumPy Random
from numpy import random

x = random.randint(100)
print(x)

x1 = random.rand()
print(x1)

x2 = random.randint(100, size=(3, 5))
print(x2)

x3 = random.rand(3, 5)
print(x3)


13
0.052138926211403924
[[71 89  1 12  7]
 [76 97 72 92 10]
 [94 92 56 64 39]]
[[0.01510397 0.8064471  0.01896222 0.33504012 0.23936198]
 [0.49766391 0.58771202 0.93010222 0.40002395 0.83463322]
 [0.95537101 0.1847178  0.88746511 0.77800942 0.22116351]]


In [13]:
# Join two arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [14]:
# Join two 2-D arrays along rows (axis=1)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [15]:
# Random Distribution
from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

y = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(y)

[5 7 5 5 7 5 5 5 7 7 7 3 5 7 5 7 7 7 7 3 7 7 7 5 5 5 5 3 3 7 7 5 7 7 7 5 3
 5 7 3 7 3 7 5 7 3 7 7 7 7 7 7 7 7 7 7 7 7 7 5 3 7 7 7 7 7 7 3 7 7 7 7 5 3
 5 5 7 5 5 7 7 7 7 3 5 5 7 7 7 7 3 5 7 5 7 7 5 7 7 7]
[[5 7 5 3 7]
 [7 7 7 7 5]
 [5 7 7 7 7]]


In [16]:
x = random.normal(size=(2, 3))
print(x)

y = random.normal(loc=1, scale=2, size=(2, 3))
print(y)

[[ 0.11089753  1.2509795   0.18145556]
 [ 0.74640213 -1.39800691  2.05433046]]
[[-3.44596291 -0.19789347  0.55703109]
 [-0.17957563  2.64852669  1.29766516]]
